apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-stage-1-emd
spec:
  secretName: secret-tls-stage-1-emd
  renewBefore: 240h
  duration: 2160h
  commonName: emd.stage1.app.staging.ecommercemd.com
  dnsNames:
  - emd.stage1.app.staging.ecommercemd.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer