apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secure-testlink
  namespace: default
spec:
  secretName: secure-testlink-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kube.testlink.me
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - kube.testlink.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io