apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-test
spec:
  secretName: secret-tls-2
  renewBefore: 240h
  duration: 2160h
  commonName: test2.testlink.me
  dnsNames:
  - test2.testlink.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer