apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - kube.testlink.me
    secretName: secure-testlink-p6658
  rules:
  - host: kube.testlink.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-project
            port:
              number: 80