apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-bilgicloud-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod # Use your appropriate ClusterIssuer name

spec:
  tls:
  - hosts:
    - test2.staging.ecommercemd.com
    secretName: secret-tls-2 # Specify the name of the secret to store the TLS certificate

  rules:
  - host: test2.staging.ecommercemd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
